theme = "base16_terminal"

[editor]
line-number = "absolute" # "absolute" | "relative"
color-modes = true
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[keys.normal]
g = { a = "code_action"} # ga opens code actions
C-q = ":wq"

[keys.normal."space"]
w = ":w" # space + w => save file
q = ":wbc" # space + q => write anc close current buffer

[keys.insert]
j = { j = "normal_mode" }

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "❖"
mode.insert = "➤"
mode.select = "{_}"

[editor.indent-guides]
render = true
character = "│"